AWSTemplateFormatVersion: '2010-09-09'
Description: 'WGA Frontend Infrastructure CloudFormation Template'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: The deployment environment
  
  DomainName:
    Type: String
    Default: ""
    Description: Domain name for the frontend (leave empty for CloudFront distribution URL only)
  
  CertificateARN:
    Type: String
    Default: ""
    Description: ARN of ACM certificate for HTTPS (required if DomainName is provided)

Resources:
  # Amplify App for frontend hosting
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: !Sub 'wga-frontend-${Environment}'
      Repository: ''
      Platform: WEB
      Description: !Sub 'Amplify App for WGA Frontend - ${Environment}'
      BuildSpec: |
        version: 1
        frontend:
          phases:
            preBuild:
              commands:
                - npm install
            build:
              commands:
                - npm run build
          artifacts:
            baseDirectory: dist
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**

  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      BranchName: main

Outputs:
  AmplifyAppId:
    Description: Amplify App ID
    Value: !GetAtt AmplifyApp.AppId
    Export:
      Name: !Sub '${AWS::StackName}-AmplifyAppId'

  AmplifyAppDefaultDomain:
    Description: Default domain of the Amplify App
    Value: !GetAtt AmplifyApp.DefaultDomain
    Export:
      Name: !Sub '${AWS::StackName}-AmplifyAppDefaultDomain'