AWSTemplateFormatVersion: '2010-09-09'
Description: 'WGA Frontend Infrastructure CloudFormation Template'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: The deployment environment

  DomainName:
    Type: String
    Default: ""
    Description: Domain name for the frontend (leave empty for CloudFront distribution URL only)

  CertificateARN:
    Type: String
    Default: ""
    Description: ARN of ACM certificate for HTTPS (required if DomainName is provided)

Resources:
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub wga-frontend-${Environment}
      AccessControl: Private

  # Amplify App for frontend hosting
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: !Sub 'wga-frontend-${Environment}'
      Repository: ''
      Platform: WEB
      Description: !Sub 'Amplify App for WGA Frontend - ${Environment}'
      BuildSpec: |
        version: 1
        frontend:
          phases:
            preBuild:
              commands:
                - npm install
            build:
              commands:
                - npm run build
          artifacts:
            baseDirectory: dist
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**

  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      BranchName: main

  # SSM Parameters
  AmplifyAppIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/wga/${Environment}/AmplifyAppId'
      Type: String
      Value: !GetAtt AmplifyApp.AppId
      Description: Amplify App ID

  AmplifyDefaultDomainParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/wga/${Environment}/AmplifyDefaultDomain'
      Type: String
      Value: !GetAtt AmplifyApp.DefaultDomain
      Description: Default domain of the Amplify App

Outputs:
  AmplifyAppId:
    Description: Amplify App ID
    Value: !GetAtt AmplifyApp.AppId

  AmplifyAppDefaultDomain:
    Description: Default domain of the Amplify App
    Value: !GetAtt AmplifyApp.DefaultDomain