AWSTemplateFormatVersion: "2010-09-09"
Description: "WGA - Main CloudFormation Template"

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: The deployment environment

  McpImageUri:  # << 이거 추가됨
    Type: "String"
    Description: ECR URI for MCP Lambda Docker image

  DeveloperMode:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: Enable developer mode (disables zero trust evaluation)

  # 파라미터 정의를 SSM 참조 방식으로 변경
  UserPoolId:
    Type: "AWS::SSM::Parameter::Value<String>"
    Default: "/wga/${Environment}/UserPoolId"
    Description: ID of the Cognito User Pool

  UserPoolClientId:
    Type: "AWS::SSM::Parameter::Value<String>"
    Default: "/wga/${Environment}/UserPoolClientId"
    Description: ID of the Cognito User Pool Client

  UserPoolDomain:
    Type: "AWS::SSM::Parameter::Value<String>"
    Default: "/wga/${Environment}/UserPoolDomain"
    Description: Domain of the Cognito User Pool

  IdentityPoolId:
    Type: "AWS::SSM::Parameter::Value<String>"
    Default: "/wga/${Environment}/IdentityPoolId"
    Description: ID of the Cognito Identity Pool

  OutputBucketName:
    Type: "AWS::SSM::Parameter::Value<String>"
    Default: "/wga/${Environment}/OutputBucketName"
    Description: Name of the output S3 bucket

  ApiGatewayIdParameter:
    Type: "AWS::SSM::Parameter::Value<String>"
    Default: "/wga/${Environment}/ApiGatewayId"
    Description: ID of the API Gateway

  ApiGatewayRootResourceIdParameter:
    Type: "AWS::SSM::Parameter::Value<String>"
    Default: "/wga/${Environment}/ApiGatewayRootResourceId"
    Description: Root Resource ID of the API Gateway

  FrontendRedirectDomainParameter:
    Type: "AWS::SSM::Parameter::Value<String>"
    Default: "/wga/${Environment}/FrontendRedirectDomain"
    Description: Frontend redirect domain

  SlackBotTokenSSMPathParameter:
    Type: "AWS::SSM::Parameter::Value<String>"
    Default: "/wga/${Environment}/SlackbotToken"
    Description: Path to the Slack Bot Token in SSM

  AthenaOutputBucketParameter:
    Type: "AWS::SSM::Parameter::Value<String>"
    Default: "/wga/${Environment}/AthenaOutputBucketName"
    Description: Athena Output Bucket Parameter

  KnowledgeBaseIdParameter:
    Type: "AWS::SSM::Parameter::Value<String>"
    Default: "/wga/${Environment}/KnowledgeBaseId"
    Description: Knowledge Base ID

Resources:
  LlmStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/wga-cloudformation-${AWS::AccountId}/llm.yaml"
      Parameters:
        Environment: !Ref Environment
        ApiGatewayId: !Ref ApiGatewayIdParameter
        ApiGatewayRootResourceId: !Ref ApiGatewayRootResourceIdParameter
        FrontendRedirectDomain: !Ref FrontendRedirectDomainParameter
        McpImageUri: !Ref McpImageUri # << 이 줄 추가
        KnowledgeBaseIdParameter: !Ref KnowledgeBaseIdParameter
      Tags:
        - Key: Environment
          Value: !Ref Environment

  DBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/wga-cloudformation-${AWS::AccountId}/logs.yaml"
      Parameters:
        Environment: !Ref Environment
        ApiGatewayId: !Ref ApiGatewayIdParameter
        ApiGatewayRootResourceId: !Ref ApiGatewayRootResourceIdParameter
        FrontendRedirectDomain: !Ref FrontendRedirectDomainParameter
        AthenaOutputBucketName: !Ref AthenaOutputBucketParameter
      Tags:
        - Key: Environment
          Value: !Ref Environment

  SlackbotStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/wga-cloudformation-${AWS::AccountId}/slackbot.yaml"
      Parameters:
        Environment: !Ref Environment
        ApiGatewayId: !Ref ApiGatewayIdParameter
        ApiGatewayRootResourceId: !Ref ApiGatewayRootResourceIdParameter
        ApiEndpointParameter: !Ref ApiEndpointParameter
        SlackBotTokenSSMPath: !Ref SlackBotTokenSSMPathParameter
        CognitoClientIdSSMPath: !Ref UserPoolClientId
        CognitoDomainSSMPath: !Ref UserPoolDomain
      Tags:
        - Key: Environment
          Value: !Ref Environment

  ChatHistoryStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/wga-cloudformation-${AWS::AccountId}/chat-history.yaml"
      Parameters:
        Environment: !Ref Environment
        ApiGatewayId: !Ref ApiGatewayIdParameter
        ApiGatewayRootResourceId: !Ref ApiGatewayRootResourceIdParameter
        FrontendRedirectDomain: !Ref FrontendRedirectDomainParameter
      Tags:
        - Key: Environment
          Value: !Ref Environment

  ApiEndpointParameter:
    Type: AWS::SSM::Parameter
    DeletionPolicy: Delete
    Properties:
      Name: !Sub "/wga/${Environment}/ApiEndpoint"
      Type: String
      Value: !Sub "https://${ApiGatewayIdParameter}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
      Description: API Gateway endpoint URL

Outputs:
  CognitoDomain:
    Description: Cognito User Pool Domain
    Value: !Ref UserPoolDomain

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPoolId

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClientId

  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ApiGatewayIdParameter}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
