AWSTemplateFormatVersion: "2010-09-09"
Description: "WGA Slackbot Service CloudFormation Template"

Parameters:
  Environment:
    Type: String
    Description: The deployment environment

  ApiEndpointParameter:
    Type: String
    Description: API Endpoint

  ApiGatewayId:
    Type: String
    Description: API Gateway ID

  ApiGatewayRootResourceId:
    Type: String
    Description: API Gateway Root Resource ID

  SlackBotTokenSSMPath:
    Type: String
    Description: Path to the Slack Bot Token in SSM Parameter Store

  CognitoClientIdSSMPath:
    Type: String
    Description: ID of the Cognito User Pool Client

  CognitoDomainSSMPath:
    Type: String
    Description: Domain of the Cognito User Pool

Resources:
  SlackbotLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "wga-slackbot-execution-role-${Environment}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SlackbotLambdaAccessSSM
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource:
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${SlackBotTokenSSMPath}"
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${CognitoClientIdSSMPath}"
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${CognitoDomainSSMPath}"

        - PolicyName: SlackbotDynamoDBSessionAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:DeleteItem
                Resource:
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/SlackbotSessions"

  SlackbotLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "wga-slackbot-${Environment}"
      Runtime: python3.12
      Handler: lambda_function.lambda_handler
      Code:
        S3Bucket: !Sub "wga-deployment-${Environment}"
        S3Key: !Sub "slackbot/slackbot-lambda-${Environment}.zip"
      Timeout: 15
      MemorySize: 256
      Role: !GetAtt SlackbotLambdaExecutionRole.Arn
      Environment:
        Variables:
          SLACK_BOT_TOKEN_PATH: !Ref SlackBotTokenSSMPath
          COGNITO_CLIENT_ID_PATH: !Ref CognitoClientIdSSMPath
          COGNITO_DOMAIN_PATH: !Ref CognitoDomainSSMPath
          API_ENDPOINT: !Ref ApiEndpointParameter
      Tags:
        - Key: Environment
          Value: !Ref Environment

  SlackbotApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGatewayId
      ParentId: !Ref ApiGatewayRootResourceId
      PathPart: "slackbot"

  SlackbotMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayId
      ResourceId: !Ref SlackbotApiResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SlackbotLambdaFunction.Arn}/invocations"
      MethodResponses:
        - StatusCode: "200"

  SlackbotLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref SlackbotLambdaFunction
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayId}/*"
